[TES-6275] Jinja Template Converter tool
katalon-studio/superset pull request #35
Opened 2024-04-16 10:47 UTC by triquanminh

## SUMMARY
- Implemented a `NodeJS` script that converts JSON SQL data to Jinja Template format
- This is used for dynamic filters when filtering chart in Superset
- With this, it will optimize the unnecessary JOIN statement before apply/adding the new filters. Only JOIN when the filter is added

2024-04-16 11:03 UTC, huynguyen2908 requested changes

2024-04-16 11:03 UTC, huynguyen2908 commented on katalon-utils/jinja-template-converter/input.json
> +      "filterNames": ["browser_name", "os_name"]
Try to remove this e.

2024-04-16 11:05 UTC, triquanminh commented on katalon-utils/jinja-template-converter/input.json
> +      "filterNames": ["browser_name", "os_name"]
- Remove `filterNames`
- Read from WHERE clause, the column will have the alias (`etr.profile`). Have a function to populate `filterNames` in `JOIN` clauses based on this

2024-04-17 04:55 UTC, huynguyen2908 approved these changes

2024-04-17 04:55 UTC, merged